base_to_footprint_ekf:
  ros__parameters:
    frequency: 20.0
    publish_tf: true
    transform_timeout: 0.01
    transform_time_offset: 0.045
    two_d_mode: false

    pose0: base_to_footprint_pose
    pose0_config: [true,  true,  true,
                  true,  true,  true,
                  false, false, false,
                  false, false, false,
                  false, false, false]

    odom_frame: base_footprint
    world_frame: base_footprint
