footprint_to_odom_ekf:
  ros__parameters:
    frequency: 20.0
    publish_tf: true
    transform_timeout: 0.01
    two_d_mode: true

    odom0: odom/raw
    odom0_config: [false, false, false,
                  false, false, false,
                    true,  true, false,
                  false, false, true,
                  false, false, false]

    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom
