/**:
  ros__parameters:
    gait.knee_orientation: ">>"
    gait.pantograph_leg: false
    gait.odom_scaler: 1.0
    gait.max_linear_velocity_x: 0.5
    gait.max_linear_velocity_y: 0.25
    gait.max_angular_velocity_z: 1.0
    gait.com_x_translation: 0.0
    gait.swing_height: 0.02
    gait.stance_depth: 0.0
    gait.stance_duration: 0.25
    gait.nominal_height: 0.15
