/**:
  ros__parameters:
    gait.knee_orientation: ">>"
    gait.pantograph_leg: false
    gait.odom_scaler: 1.0
    gait.max_linear_velocity_x: 0.12
    gait.max_linear_velocity_y: 0.1
    gait.max_angular_velocity_z: 0.6
    gait.com_x_translation: 0.02
    gait.swing_height: 0.07
    gait.stance_depth: 0.0
    gait.stance_duration: 0.6
    gait.nominal_height: 0.15
