/**:
  ros__parameters:
    gait.knee_orientation: ">>"
    gait.pantograph_leg: false
    gait.odom_scaler: 1.0
    gait.max_linear_velocity_x: 0.05
    gait.max_linear_velocity_y: 0.05
    gait.max_angular_velocity_z: 0.3
    gait.com_x_translation: 0.03
    gait.swing_height: 0.10
    gait.stance_depth: 0.0
    gait.stance_duration: 1.0
    gait.nominal_height: 0.18