apiVersion: v1
kind: ConfigMap
metadata:
  name: spot-lcd-rust-config
  labels:
    app.kubernetes.io/name: spot-lcd-rust
    app.kubernetes.io/part-of: spot
data:
  lcd_config.toml: |
    # Configuration for LCD display
    [lcd]
    pin_rs = 25
    pin_en = 24
    pins_data = [23, 17, 18, 22]
    cols = 16
    rows = 2
    
    [temp_monitor]
    interval = 5
    
    [uptime_monitor]
    interval = 10
    
    [ros_publisher]
    temp_topic = "lcd_temperature"
    uptime_topic = "lcd_uptime"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: spot-lcd-rust
  labels:
    app.kubernetes.io/name: spot-lcd-rust
    app.kubernetes.io/part-of: spot
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: spot-lcd-rust
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spot-lcd-rust
        app.kubernetes.io/part-of: spot
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
        gorizond.io/robot: "true"
        gorizond.io/spot-lcd: "true"
      containers:
        - name: lcd-display
          image: ghcr.io/gorizond/spot-lcd-rust:latest
          imagePullPolicy: Always
          command:
          - /usr/local/bin/spot_lcd_node
          args:
          - --module
          - all
          securityContext:
            privileged: true
            runAsUser: 0
            runAsGroup: 0
            allowPrivilegeEscalation: true
          env:
            - name: RUST_LOG
              value: "info"
          volumeMounts:
            - name: spot-lcd-rust-config-volume
              mountPath: /app/config
            - name: host-proc
              mountPath: /host/proc
              readOnly: true
            - name: host-sys
              mountPath: /host/sys
              readOnly: true
            - name: gpiomem
              mountPath: /dev/gpiomem
      volumes:
        - name: spot-lcd-rust-config-volume
          configMap:
            name: spot-lcd-rust-config
        - name: host-proc
          hostPath:
            path: /proc
            type: Directory
        - name: host-sys
          hostPath:
            path: /sys
            type: Directory
        - name: gpiomem
          hostPath:
            path: /dev/gpiomem
            type: CharDevice