apiVersion: v1
kind: ConfigMap
metadata:
  name: spot-lcd-cpp-config
  labels:
    app.kubernetes.io/name: spot-lcd-cpp
    app.kubernetes.io/part-of: spot
data:
  lcd_config.toml: |
    # Configuration for LCD display
    [lcd]
    pin_rs = 25
    pin_en = 24
    pins_data = [23, 17, 18, 22]
    cols = 16
    rows = 2
    refresh_interval = 10
    
    [temp_monitor]
    interval = 10
    
    [uptime_monitor]
    interval = 10
---
# DaemonSet for LCD display node (handles LCD display and subscribes to temp/uptime topics)
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: spot-lcd-display
  labels:
    app.kubernetes.io/name: spot-lcd-display
    app.kubernetes.io/part-of: spot
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: spot-lcd-display
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spot-lcd-display
        app.kubernetes.io/part-of: spot
      annotations:
        spot.gorizond.io/rev: "10f349d"
    spec:
      hostPID: true  # Required for GPIO access
      hostNetwork: true  # Required for direct GPIO access
      nodeSelector:
        kubernetes.io/arch: arm64
        gorizond.io/robot: "true"
        gorizond.io/spot-lcd: "true"
      containers:
        - name: lcd-display
          image: ghcr.io/gorizond/spot-lcd-cpp:latest
          imagePullPolicy: Always
          command: ["/usr/local/bin/run_node.sh"]
          args: ["lcd"]
          securityContext:
            privileged: true
            runAsUser: 0
            runAsGroup: 0
            allowPrivilegeEscalation: true
          env:
            - name: CXX_LOG_LEVEL
              value: "info"
            - name: LCD_REFRESH_INTERVAL
              value: "10"
            - name: LCD_TEMP_LINE
              value: "0"
            - name: LCD_UPTIME_LINE
              value: "1"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "350m"
              memory: "256Mi"
          volumeMounts:
            - name: spot-lcd-cpp-config-volume
              mountPath: /app/config
            - name: gpiomem
              mountPath: /dev/gpiomem
            - name: gpiochip0
              mountPath: /dev/gpiochip0
            - name: device-tree
              mountPath: /proc/device-tree
              readOnly: true
            - name: cpuinfo
              mountPath: /proc/cpuinfo
              readOnly: true
      volumes:
        - name: spot-lcd-cpp-config-volume
          configMap:
            name: spot-lcd-cpp-config
        - name: gpiomem
          hostPath:
            path: /dev/gpiomem
            type: CharDevice
        - name: gpiochip0
          hostPath:
            path: /dev/gpiochip0
            type: CharDevice
        - name: device-tree
          hostPath:
            path: /proc/device-tree
            type: Directory
        - name: cpuinfo
          hostPath:
            path: /proc/cpuinfo
            type: File
---
# DaemonSet for temperature monitoring node (publishes temperature data to ROS2 topics)
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: spot-temp-monitor
  labels:
    app.kubernetes.io/name: spot-temp-monitor
    app.kubernetes.io/part-of: spot
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: spot-temp-monitor
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spot-temp-monitor
        app.kubernetes.io/part-of: spot
      annotations:
        spot.gorizond.io/rev: "10f349d"
    spec:
      hostPID: true  # Required for accessing system files
      hostNetwork: true  # ROS2 DDS discovery across pods
      nodeSelector:
        kubernetes.io/arch: arm64
        gorizond.io/robot: "true"
        gorizond.io/spot-lcd: "true"
      containers:
        - name: temp-monitor
          image: ghcr.io/gorizond/spot-lcd-cpp:latest
          imagePullPolicy: Always
          command: ["/usr/local/bin/run_node.sh"]
          args: ["temperature"]
          env:
            - name: CXX_LOG_LEVEL
              value: "info"
            - name: TEMP_PUB_LINE
              value: "1"
            - name: TEMP_PUB_COL
              value: "0"
            - name: TEMP_PUB_WIDTH
              value: "8"
          resources:
            requests:
              cpu: "50m"
              memory: "96Mi"
            limits:
              cpu: "200m"
              memory: "192Mi"
          volumeMounts:
            - name: spot-lcd-cpp-config-volume
              mountPath: /app/config
            - name: proc
              mountPath: /proc
              readOnly: true
      volumes:
        - name: spot-lcd-cpp-config-volume
          configMap:
            name: spot-lcd-cpp-config
        - name: proc
          hostPath:
            path: /proc
            type: Directory
---
# DaemonSet for uptime monitoring node (publishes uptime data to ROS2 topics)
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: spot-uptime-monitor
  labels:
    app.kubernetes.io/name: spot-uptime-monitor
    app.kubernetes.io/part-of: spot
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: spot-uptime-monitor
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spot-uptime-monitor
        app.kubernetes.io/part-of: spot
      annotations:
        spot.gorizond.io/rev: "10f349d"
    spec:
      hostPID: true  # Required for accessing system files
      hostNetwork: true  # ROS2 DDS discovery across pods
      nodeSelector:
        kubernetes.io/arch: arm64
        gorizond.io/robot: "true"
        gorizond.io/spot-lcd: "true"
      containers:
        - name: uptime-monitor
          image: ghcr.io/gorizond/spot-lcd-cpp:latest
          imagePullPolicy: Always
          command: ["/usr/local/bin/run_node.sh"]
          args: ["uptime"]
          env:
            - name: CXX_LOG_LEVEL
              value: "info"
            - name: UPTIME_PUB_LINE
              value: "2"
            - name: UPTIME_PUB_COL
              value: "0"
            - name: UPTIME_PUB_WIDTH
              value: "8"
          resources:
            requests:
              cpu: "50m"
              memory: "96Mi"
            limits:
              cpu: "200m"
              memory: "192Mi"
          volumeMounts:
            - name: spot-lcd-cpp-config-volume
              mountPath: /app/config
            - name: proc
              mountPath: /proc
              readOnly: true
      volumes:
        - name: spot-lcd-cpp-config-volume
          configMap:
            name: spot-lcd-cpp-config
        - name: proc
          hostPath:
            path: /proc
            type: Directory