apiVersion: v1
kind: ConfigMap
metadata:
  name: spot-lcd-cpp-config
  labels:
    app.kubernetes.io/name: spot-lcd-cpp
    app.kubernetes.io/part-of: spot
data:
  lcd_config.toml: |
    # Configuration for LCD display
    [lcd]
    pin_rs = 25
    pin_en = 24
    pins_data = [23, 17, 18, 22]
    cols = 16
    rows = 2
    
    [temp_monitor]
    interval = 5
    
    [uptime_monitor]
    interval = 10
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: spot-lcd-cpp
  labels:
    app.kubernetes.io/name: spot-lcd-cpp
    app.kubernetes.io/part-of: spot
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: spot-lcd-cpp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spot-lcd-cpp
        app.kubernetes.io/part-of: spot
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
        gorizond.io/robot: "true"
        gorizond.io/spot-lcd: "true"
      initContainers:
        - name: device-info-check
          image: busybox:1.35
          command:
            - /bin/sh
            - -c
            - |
              # Create directory for device info
              mkdir -p /device-info
              
              # Check if device tree revision file exists and copy it
              if [ -f /host/proc/device-tree/system/linux,revision ]; then
                cp /host/proc/device-tree/system/linux,revision /device-info/
                echo "Found linux,revision file"
              elif [ -f /host/proc/device-tree/system/linux,Revision ]; then
                cp /host/proc/device-tree/system/linux,Revision /device-info/
                echo "Found linux,Revision file"
              else
                echo "Warning: Could not find system revision file"
                
                # Try alternative locations
                if [ -f /host/proc/device-tree/revision ]; then
                  cp /host/proc/device-tree/revision /device-info/
                  echo "Found revision file at /device-tree/revision"
                elif [ -f /host/proc/device-tree/soc/ranges ]; then
                  cp /host/proc/device-tree/soc/ranges /device-info/ 2>/dev/null || echo "Could not copy ranges file"
                fi
              fi
              
              # Copy cpuinfo and check for Hardware line
              if [ -f /host/proc/cpuinfo ]; then
                cp /host/proc/cpuinfo /device-info/
                if grep -q "Hardware" /host/proc/cpuinfo; then
                  echo "Found Hardware line in cpuinfo"
                else
                  echo "No Hardware line found in cpuinfo, creating fallback"
                  echo "Hardware : BCM2835" > /device-info/hardware_fallback
                fi
              fi
              
              # Create additional files that might be needed by wiringPi
              if [ -f /host/proc/device-tree/model ]; then
                cp /host/proc/device-tree/model /device-info/
              fi
              
              # Check for serial number
              if [ -f /host/proc/device-tree/serial-number ]; then
                cp /host/proc/device-tree/serial-number /device-info/
              fi
              
              # List all files in device-info for debugging
              ls -la /device-info/
          securityContext:
            privileged: false
            runAsUser: 0
            runAsGroup: 0
          volumeMounts:
            - name: host-proc
              mountPath: /host/proc
              readOnly: true
            - name: device-info-volume
              mountPath: /device-info
          resources:
            limits:
              cpu: 50m
              memory: 32Mi
            requests:
              cpu: 10m
              memory: 16Mi
      containers:
        - name: lcd-display
          image: ghcr.io/gorizond/spot-lcd-cpp:latest
          imagePullPolicy: Always
          command:
          - /bin/sh
          - -c
          - |
            # Wait a moment for system to stabilize
            sleep 2
            
            # Create a fake device tree in a temporary location
            FAKE_SYSFS="/tmp/fake_sysfs"
            mkdir -p "$FAKE_SYSFS/proc/device-tree/system"
            
            # Create a fake revision file based on common Raspberry Pi values
            echo -ne '\x00\x00\x00\x00' > "$FAKE_SYSFS/proc/device-tree/system/linux,revision"  # Common fake value
            
            # Create a fake cpuinfo with hardware info
            mkdir -p "$FAKE_SYSFS/proc"
            cat > "$FAKE_SYSFS/proc/cpuinfo" << 'EOF'
            processor	: 0
            model name	: ARMv7 Processor rev 4 (v7l)
            BogoMIPS	: 38.40
            Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
            CPU implementer	: 0x41
            CPU architecture: 7
            CPU variant	: 0x0
            CPU part	: 0xd03
            CPU revision	: 4
            
            processor	: 1
            model name	: ARMv7 Processor rev 4 (v7l)
            BogoMIPS	: 38.40
            Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
            CPU implementer	: 0x41
            CPU architecture: 7
            CPU variant	: 0x0
            CPU part	: 0xd03
            CPU revision	: 4
            
            processor	: 2
            model name	: ARMv7 Processor rev 4 (v7l)
            BogoMIPS	: 38.40
            Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
            CPU implementer	: 0x41
            CPU architecture: 7
            CPU variant	: 0x0
            CPU part	: 0xd03
            CPU revision	: 4
            
            processor	: 3
            model name	: ARMv7 Processor rev 4 (v7l)
            BogoMIPS	: 38.40
            Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
            CPU implementer	: 0x41
            CPU architecture: 7
            CPU variant	: 0x0
            CPU part	: 0xd03
            CPU revision	: 4
            
            Hardware	: BCM2835
            Revision	: a020d3
            Serial		: 0000000012345678
            Model		: Raspberry Pi 3 Model B Plus Rev 1.3
EOF
            
            # Now use mount namespaces to make these files visible to wiringPi
            # First check if we can mount (we have privileged access)
            if [ -w /proc/self/ns/mnt ]; then
                # Create a new mount namespace
                unshare -m --propagation slave sh -c '
                    # Mount our fake files over the real ones (inside this namespace)
                    mount --bind "'$FAKE_SYSFS'/proc/device-tree" /proc/device-tree 2>/dev/null || true
                    mount --bind "'$FAKE_SYSFS'/proc/cpuinfo" /proc/cpuinfo 2>/dev/null || true
                    
                    # Export environment variables to help wiringPi
                    export WIRINGPI_GPIOMEM=1
                    export BCM2835_NO_ERROR=1
                    
                    # Run the application in this namespace
                    exec /usr/local/bin/spot_lcd_cpp_node -m all
                '
            else
                # If we can't create a new namespace, try the older approach
                mount --bind "$FAKE_SYSFS/proc/device-tree" /proc/device-tree 2>/dev/null || true
                mount --bind "$FAKE_SYSFS/proc/cpuinfo" /proc/cpuinfo 2>/dev/null || true
                
                # Export environment variables to help wiringPi
                export WIRINGPI_GPIOMEM=1
                export BCM2835_NO_ERROR=1
                
                # Run the application
                exec /usr/local/bin/spot_lcd_cpp_node -m all
            fi
          securityContext:
            privileged: true
            runAsUser: 0
            runAsGroup: 0
            allowPrivilegeEscalation: true
          env:
            - name: CXX_LOG_LEVEL
              value: "info"
          volumeMounts:
            - name: spot-lcd-cpp-config-volume
              mountPath: /app/config
            - name: host-proc
              mountPath: /proc
              readOnly: true
            - name: host-sys
              mountPath: /sys
              readOnly: true
            - name: host-device-tree
              mountPath: /proc/device-tree
              readOnly: true
            - name: host-cpuinfo
              mountPath: /proc/cpuinfo
              readOnly: true
            - name: device-info-volume
              mountPath: /tmp/device-info
            - name: gpiomem
              mountPath: /dev/gpiomem
      volumes:
        - name: spot-lcd-cpp-config-volume
          configMap:
            name: spot-lcd-cpp-config
        - name: host-proc
          hostPath:
            path: /proc
            type: Directory
        - name: host-sys
          hostPath:
            path: /sys
            type: Directory
        - name: host-device-tree
          hostPath:
            path: /proc/device-tree
            type: Directory
        - name: host-cpuinfo
          hostPath:
            path: /proc/cpuinfo
            type: File
        - name: device-info-volume
          emptyDir: {}
        - name: gpiomem
          hostPath:
            path: /dev/gpiomem
            type: CharDevice