apiVersion: v1
kind: ConfigMap
metadata:
  name: spot-stereo-c270-config
data:
  usb_cam_left.yaml: |
    /**:
      ros__parameters:
        video_device: "__LEFT_VIDEO_DEVICE__"
        framerate: 15.0
        io_method: "mmap"
        frame_id: "stereo_left_optical_frame"
        pixel_format: "mjpeg2rgb"
        av_device_format: "YUV422P"
        image_width: 640
        image_height: 480
        camera_name: "stereo_left"
        camera_info_url: "file:///config/stereo_left.yaml"

  usb_cam_right.yaml: |
    /**:
      ros__parameters:
        video_device: "__RIGHT_VIDEO_DEVICE__"
        framerate: 15.0
        io_method: "mmap"
        frame_id: "stereo_right_optical_frame"
        pixel_format: "mjpeg2rgb"
        av_device_format: "YUV422P"
        image_width: 640
        image_height: 480
        camera_name: "stereo_right"
        camera_info_url: "file:///config/stereo_right.yaml"

  stereo_left.yaml: |
    image_width: 640
    image_height: 480
    camera_name: stereo_left
    camera_matrix:
      rows: 3
      cols: 3
      data:
      - 720.4267073195819
      - 0.0
      - 315.7349686685138
      - 0.0
      - 719.9836035982173
      - 256.6732661725091
      - 0.0
      - 0.0
      - 1.0
    distortion_model: plumb_bob
    distortion_coefficients:
      rows: 1
      cols: 5
      data:
      - 0.005707010124622469
      - 0.7630553645642908
      - 0.006245505045239368
      - -1.535213084607296e-05
      - -1.7944341661022236
    rectification_matrix:
      rows: 3
      cols: 3
      data:
      - 0.9997701355168741
      - 0.015244185266465628
      - -0.015076171401683422
      - -0.014777107346441942
      - 0.9994218020637954
      - 0.030621865684959435
      - 0.015534259784199448
      - -0.030392044602455377
      - 0.9994173354499307
    projection_matrix:
      rows: 3
      cols: 4
      data:
      - 771.3400185619274
      - 0.0
      - 328.74793243408203
      - 0.0
      - 0.0
      - 771.3400185619274
      - 230.5443172454834
      - 0.0
      - 0.0
      - 0.0
      - 1.0
      - 0.0

  stereo_right.yaml: |
    image_width: 640
    image_height: 480
    camera_name: stereo_right
    camera_matrix:
      rows: 3
      cols: 3
      data:
      - 721.8051392933522
      - 0.0
      - 341.04480982066093
      - 0.0
      - 721.242556071498
      - 255.58851005478834
      - 0.0
      - 0.0
      - 1.0
    distortion_model: plumb_bob
    distortion_coefficients:
      rows: 1
      cols: 5
      data:
      - 0.0239595432210842
      - 0.5954206809214123
      - 0.002563313386630115
      - 0.0009298608997851385
      - -1.6040777400215815
    rectification_matrix:
      rows: 3
      cols: 3
      data:
      - 0.9996630184107447
      - 0.02068115924476558
      - 0.015688826412826817
      - -0.021243054422392344
      - 0.999106508559997
      - 0.03653651860618241
      - -0.014919191021179466
      - -0.036857485065387774
      - 0.9992091590522618
    projection_matrix:
      rows: 3
      cols: 4
      data:
      - 771.3400185619274
      - 0.0
      - 328.74793243408203
      - -71.0303526081743
      - 0.0
      - 771.3400185619274
      - 230.5443172454834
      - 0.0
      - 0.0
      - 0.0
      - 1.0
      - 0.0

  run-left.sh: |
    #!/usr/bin/env bash
    set -eo pipefail

    source /opt/ros/kilted/setup.bash

    LEFT_VIDEO_DEVICE="${LEFT_VIDEO_DEVICE:-/host-dev/v4l/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.1:1.0-video-index0}"
    STEREO_NAMESPACE="${STEREO_NAMESPACE:-stereo}"

    echo "[spot-stereo-c270-left] LEFT_VIDEO_DEVICE=${LEFT_VIDEO_DEVICE}"
    echo "[spot-stereo-c270-left] STEREO_NAMESPACE=${STEREO_NAMESPACE}"

    wait_for_device() {
      local dev="$1"
      local retries="${2:-60}"

      for _ in $(seq 1 "${retries}"); do
        if [ -e "${dev}" ]; then
          return 0
        fi
        sleep 1
      done

      echo "[spot-stereo-c270-left] ERROR: device not found: ${dev}" >&2
      return 1
    }

    resolve_video_device() {
      local dev="$1"
      local target
      local candidate
      local video

      if [ -L "${dev}" ]; then
        target="$(readlink "${dev}" 2>/dev/null || true)"
        video="$(echo "${target}" | grep -oE 'video[0-9]+' | head -n1 || true)"
        if [ -n "${video}" ]; then
          echo "/dev/${video}"
          return 0
        fi
      fi

      candidate="$(readlink -f "${dev}" 2>/dev/null || echo "${dev}")"
      video="$(echo "${candidate}" | grep -oE 'video[0-9]+' | head -n1 || true)"
      if [ -n "${video}" ]; then
        echo "/dev/${video}"
        return 0
      fi

      case "${candidate}" in
        /host-dev/*)
          candidate="/dev/${candidate#/host-dev/}"
          ;;
      esac

      echo "${candidate}"
    }

    wait_for_device "${LEFT_VIDEO_DEVICE}"
    LEFT_VIDEO_DEVICE_RESOLVED="$(resolve_video_device "${LEFT_VIDEO_DEVICE}")"
    echo "[spot-stereo-c270-left] LEFT_VIDEO_DEVICE_RESOLVED=${LEFT_VIDEO_DEVICE_RESOLVED}"
    wait_for_device "${LEFT_VIDEO_DEVICE_RESOLVED}"

    mkdir -p /tmp/spot-stereo
    cp /config/usb_cam_left.yaml /tmp/spot-stereo/usb_cam_left.yaml
    sed -i "s|__LEFT_VIDEO_DEVICE__|${LEFT_VIDEO_DEVICE_RESOLVED}|g" /tmp/spot-stereo/usb_cam_left.yaml

    PIDS=()

    start_bg() {
      "$@" &
      PIDS+=("$!")
    }

    start_bg ros2 run usb_cam usb_cam_node_exe       --ros-args       --remap __ns:=/${STEREO_NAMESPACE}/left       --params-file /tmp/spot-stereo/usb_cam_left.yaml

    start_bg ros2 launch image_proc image_proc.launch.py       namespace:=${STEREO_NAMESPACE}/left

    cleanup() {
      kill "${PIDS[@]}" 2>/dev/null || true
      wait "${PIDS[@]}" 2>/dev/null || true
    }
    trap cleanup EXIT INT TERM

    wait -n "${PIDS[@]}"
    exit $?

  run-right.sh: |
    #!/usr/bin/env bash
    set -eo pipefail

    source /opt/ros/kilted/setup.bash

    RIGHT_VIDEO_DEVICE="${RIGHT_VIDEO_DEVICE:-/host-dev/v4l/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.2:1.0-video-index0}"
    STEREO_NAMESPACE="${STEREO_NAMESPACE:-stereo}"

    echo "[spot-stereo-c270-right] RIGHT_VIDEO_DEVICE=${RIGHT_VIDEO_DEVICE}"
    echo "[spot-stereo-c270-right] STEREO_NAMESPACE=${STEREO_NAMESPACE}"

    wait_for_device() {
      local dev="$1"
      local retries="${2:-60}"

      for _ in $(seq 1 "${retries}"); do
        if [ -e "${dev}" ]; then
          return 0
        fi
        sleep 1
      done

      echo "[spot-stereo-c270-right] ERROR: device not found: ${dev}" >&2
      return 1
    }

    resolve_video_device() {
      local dev="$1"
      local target
      local candidate
      local video

      if [ -L "${dev}" ]; then
        target="$(readlink "${dev}" 2>/dev/null || true)"
        video="$(echo "${target}" | grep -oE 'video[0-9]+' | head -n1 || true)"
        if [ -n "${video}" ]; then
          echo "/dev/${video}"
          return 0
        fi
      fi

      candidate="$(readlink -f "${dev}" 2>/dev/null || echo "${dev}")"
      video="$(echo "${candidate}" | grep -oE 'video[0-9]+' | head -n1 || true)"
      if [ -n "${video}" ]; then
        echo "/dev/${video}"
        return 0
      fi

      case "${candidate}" in
        /host-dev/*)
          candidate="/dev/${candidate#/host-dev/}"
          ;;
      esac

      echo "${candidate}"
    }

    wait_for_device "${RIGHT_VIDEO_DEVICE}"
    RIGHT_VIDEO_DEVICE_RESOLVED="$(resolve_video_device "${RIGHT_VIDEO_DEVICE}")"
    echo "[spot-stereo-c270-right] RIGHT_VIDEO_DEVICE_RESOLVED=${RIGHT_VIDEO_DEVICE_RESOLVED}"
    wait_for_device "${RIGHT_VIDEO_DEVICE_RESOLVED}"

    mkdir -p /tmp/spot-stereo
    cp /config/usb_cam_right.yaml /tmp/spot-stereo/usb_cam_right.yaml
    sed -i "s|__RIGHT_VIDEO_DEVICE__|${RIGHT_VIDEO_DEVICE_RESOLVED}|g" /tmp/spot-stereo/usb_cam_right.yaml

    PIDS=()

    start_bg() {
      "$@" &
      PIDS+=("$!")
    }

    start_bg ros2 run usb_cam usb_cam_node_exe       --ros-args       --remap __ns:=/${STEREO_NAMESPACE}/right       --params-file /tmp/spot-stereo/usb_cam_right.yaml

    start_bg ros2 launch image_proc image_proc.launch.py       namespace:=${STEREO_NAMESPACE}/right

    cleanup() {
      kill "${PIDS[@]}" 2>/dev/null || true
      wait "${PIDS[@]}" 2>/dev/null || true
    }
    trap cleanup EXIT INT TERM

    wait -n "${PIDS[@]}"
    exit $?

  run-stereo-core.sh: |
    #!/usr/bin/env bash
    set -eo pipefail

    source /opt/ros/kilted/setup.bash

    STEREO_NAMESPACE="${STEREO_NAMESPACE:-stereo}"
    APPROX_SYNC_TOLERANCE="${APPROX_SYNC_TOLERANCE:-0.12}"
    DISPARITY_RANGE="${DISPARITY_RANGE:-192}"

    echo "[spot-stereo-c270-core] STEREO_NAMESPACE=${STEREO_NAMESPACE}"
    echo "[spot-stereo-c270-core] APPROX_SYNC_TOLERANCE=${APPROX_SYNC_TOLERANCE}"
    echo "[spot-stereo-c270-core] DISPARITY_RANGE=${DISPARITY_RANGE}"

    PIDS=()

    start_bg() {
      "$@" &
      PIDS+=("$!")
    }

    start_bg ros2 run stereo_image_proc disparity_node --ros-args       --remap __ns:=/${STEREO_NAMESPACE}       -p approximate_sync:=true       -p approximate_sync_tolerance_seconds:=${APPROX_SYNC_TOLERANCE}       -p disparity_range:=${DISPARITY_RANGE}       --remap left/camera_info:=/${STEREO_NAMESPACE}/left/camera_info       --remap right/camera_info:=/${STEREO_NAMESPACE}/right/camera_info       --remap left/image_rect:=/${STEREO_NAMESPACE}/left/image_rect       --remap right/image_rect:=/${STEREO_NAMESPACE}/right/image_rect

    start_bg ros2 run stereo_image_proc point_cloud_node --ros-args       --remap __ns:=/${STEREO_NAMESPACE}       -p approximate_sync:=true       -p approximate_sync_tolerance_seconds:=${APPROX_SYNC_TOLERANCE}       -p avoid_point_cloud_padding:=true       --remap disparity:=/${STEREO_NAMESPACE}/disparity       --remap left/camera_info:=/${STEREO_NAMESPACE}/left/camera_info       --remap right/camera_info:=/${STEREO_NAMESPACE}/right/camera_info       --remap left/image_rect_color:=/${STEREO_NAMESPACE}/left/image_rect_color

    cleanup() {
      kill "${PIDS[@]}" 2>/dev/null || true
      wait "${PIDS[@]}" 2>/dev/null || true
    }
    trap cleanup EXIT INT TERM

    wait -n "${PIDS[@]}"
    exit $?
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: spot-stereo-c270-left
  labels:
    app.kubernetes.io/name: spot-stereo-c270-left
    app.kubernetes.io/part-of: spot
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: spot-stereo-c270-left
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spot-stereo-c270-left
        app.kubernetes.io/part-of: spot
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
        gorizond.io/robot: "true"
        gorizond.io/spot-stereo: "true"
      containers:
        - name: stereo-c270-left
          image: ghcr.io/gorizond/spot-stereo-c270:latest
          imagePullPolicy: Always
          securityContext:
            privileged: true
            runAsUser: 0
            runAsGroup: 0
            allowPrivilegeEscalation: true
          env:
            - name: RMW_IMPLEMENTATION
              value: "rmw_cyclonedds_cpp"
            - name: STEREO_NAMESPACE
              value: "stereo"
            - name: LEFT_VIDEO_DEVICE
              value: "/host-dev/v4l/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.1:1.0-video-index0"
          command: ["bash", "-lc"]
          args:
            - |
              set -eo pipefail
              /config/run-left.sh
          volumeMounts:
            - name: host-dev
              mountPath: /host-dev
            - name: stereo-config
              mountPath: /config
              readOnly: true
      volumes:
        - name: host-dev
          hostPath:
            path: /dev
            type: Directory
        - name: stereo-config
          configMap:
            name: spot-stereo-c270-config
            defaultMode: 0555
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: spot-stereo-c270-right
  labels:
    app.kubernetes.io/name: spot-stereo-c270-right
    app.kubernetes.io/part-of: spot
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: spot-stereo-c270-right
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spot-stereo-c270-right
        app.kubernetes.io/part-of: spot
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
        gorizond.io/robot: "true"
        gorizond.io/spot-stereo: "true"
      containers:
        - name: stereo-c270-right
          image: ghcr.io/gorizond/spot-stereo-c270:latest
          imagePullPolicy: Always
          securityContext:
            privileged: true
            runAsUser: 0
            runAsGroup: 0
            allowPrivilegeEscalation: true
          env:
            - name: RMW_IMPLEMENTATION
              value: "rmw_cyclonedds_cpp"
            - name: STEREO_NAMESPACE
              value: "stereo"
            - name: RIGHT_VIDEO_DEVICE
              value: "/host-dev/v4l/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.2:1.0-video-index0"
          command: ["bash", "-lc"]
          args:
            - |
              set -eo pipefail
              /config/run-right.sh
          volumeMounts:
            - name: host-dev
              mountPath: /host-dev
            - name: stereo-config
              mountPath: /config
              readOnly: true
      volumes:
        - name: host-dev
          hostPath:
            path: /dev
            type: Directory
        - name: stereo-config
          configMap:
            name: spot-stereo-c270-config
            defaultMode: 0555
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: spot-stereo-c270-core
  labels:
    app.kubernetes.io/name: spot-stereo-c270-core
    app.kubernetes.io/part-of: spot
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: spot-stereo-c270-core
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spot-stereo-c270-core
        app.kubernetes.io/part-of: spot
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
        gorizond.io/robot: "true"
        gorizond.io/spot-stereo: "true"
      containers:
        - name: stereo-c270-core
          image: ghcr.io/gorizond/spot-stereo-c270:latest
          imagePullPolicy: Always
          securityContext:
            privileged: true
            runAsUser: 0
            runAsGroup: 0
            allowPrivilegeEscalation: true
          env:
            - name: RMW_IMPLEMENTATION
              value: "rmw_cyclonedds_cpp"
            - name: STEREO_NAMESPACE
              value: "stereo"
            - name: APPROX_SYNC_TOLERANCE
              value: "0.12"
            - name: DISPARITY_RANGE
              value: "192"
          command: ["bash", "-lc"]
          args:
            - |
              set -eo pipefail
              /config/run-stereo-core.sh
          volumeMounts:
            - name: stereo-config
              mountPath: /config
              readOnly: true
      volumes:
        - name: stereo-config
          configMap:
            name: spot-stereo-c270-config
            defaultMode: 0555
