/**:
  ros__parameters:
    links_map.left_front:
      - front_left_shoulder_link
      - front_left_leg_link
      - front_left_foot_link
      - front_left_toe_link

    links_map.right_front:
      - front_right_shoulder_link
      - front_right_leg_link
      - front_right_foot_link
      - front_right_toe_link

    links_map.left_hind:
      - rear_left_shoulder_link
      - rear_left_leg_link
      - rear_left_foot_link
      - rear_left_toe_link

    links_map.right_hind:
      - rear_right_shoulder_link
      - rear_right_leg_link
      - rear_right_foot_link
      - rear_right_toe_link
